server:
  port: 8080
  servlet-path: /

person:
  name: 张三
  age: 18

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///spring_boot
    username: root
    password: xuan
  jpa:
    hibernate:
      ddl-auto: update
      #naming:
        #physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #禁用jpa的驼峰命名
    show-sql: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:com.heima.mapper/*.xml
  type-aliases-package: com.heima.domain


